### PR TITLE
Upgrade versions of PyFR and ParaView

### PR DESCRIPTION
**Pull request by cjh1**
When ParaView 5.4 hit I will also update or AMI

### CODE REVIEW

**Comment by cjh1** [comment]
@TristanWright Can you test out these updates please?

**Comment by TristanWright** [comment]
Can I do a `provision` to update or do I need a fresh vm?

**Comment by cjh1** [comment]
Fresh vm

**Comment by TristanWright** [comment]
All looks good to me.

**Review by TristanWright — APPROVED** [review]

**Pull request merged**
