### PR TITLE
Bind to all interface for Vagrant deploy

### PR DESCRIPTION
**Pull request by cjh1**
@jourdain This should resolve you issue, if you would like to give is a try.

### CODE REVIEW

**Comment by jourdain** [comment]
How do I test? Should I start from scratch?

**Comment by cjh1** [comment]
@jourdain Yes, a fresh ```vagrant up```

**Comment by jourdain** [comment]
ok I'll run it in the background...

**Comment by jourdain** [comment]
it is working

**Comment by cjh1** [comment]
@jourdain Awesome, can you approve the PR. Thanks.

**Review by jourdain — APPROVED** [review]

**Pull request merged**
