### PR TITLE
Fix up init.d script for celery

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
@jourdain When you recreate you vm can you try this branch, it should solve the celery restart issue you where seeing.

**Comment by jourdain** [comment]
I've already created my VM and I've already spent some time filling the database with meaningful content. So I can try, but will ssh to it...

**Comment by cjh1** [comment]
Sure:

```
vagrant ssh
sudo vim /etc/init.d/celeryd

Change line 56 to:

CELERY_DEFAULTS=${CELERY_DEFAULTS:-"/etc/default/celeryd"}
```

**Comment by cjh1** [comment]
@kotfic Could you review the last commit, it fixes up the plugin_path issue, thanks

**Comment by kotfic** [comment]
@cjh1 LGTM -  though i'm hoping to refactor this tomorrow to use the new girder-install scripts

**Pull request merged**
